# Generated by Django 2.1.4 on 2019-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritiontips',
            options={'ordering': ['-tip']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
