# Generated by Django 2.1.4 on 2019-09-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0002_auto_20190908_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritiontips',
            options={'ordering': ['-pk']},
        ),
    ]
