# Generated by Django 2.1.4 on 2019-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0003_auto_20190908_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiontips',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
