# Generated by Django 2.1.4 on 2019-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0004_nutritiontips_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiontips',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
