# Generated by Django 2.1.4 on 2019-09-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0006_auto_20190908_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritiontips',
            options={'ordering': ['-pub_date']},
        ),
    ]
