# Generated by Django 2.1.4 on 2019-09-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0007_auto_20190908_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritiontips',
            options={'ordering': ['-id']},
        ),
    ]
