# Generated by Django 2.1.4 on 2019-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0010_auto_20190908_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritiontips',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
