# Generated by Django 2.1.4 on 2019-09-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0011_auto_20190909_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('briefing', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='treated/')),
            ],
        ),
    ]
