# Generated by Django 2.1.4 on 2019-09-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0012_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
